#!/usr/bin/env groovy

//****************************************************************************
// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// Find the sum of all the even-valued terms in the sequence which do not
// exceed four million.
//****************************************************************************

def max = 4000000

def fibs = []
def (a,b) = [0,1]
while (b < max) {
    fibs << b
    (a,b) = [b,a+b]
}
println fibs.findAll { it % 2 == 0 }.sum()
