#!/usr/bin/env ruby

#****************************************************************************
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not
# exceed four million.
#****************************************************************************

class Fibs
  include Enumerable
  def each
    a,b = 1,1
    loop do
      yield b
      a,b = b,a+b
    end
  end
end
fibs = Fibs.new
puts fibs.take_while { |i| i < 4_000_000 }.find_all { |i| i.even? }.reduce(:+)

